version: '3.9'

services:

  docker-node-web-app:
    container_name: node-web-app
    build:
      context: .
      dockerfile: ./conf/docker/development/Dockerfile
    command: npm start --prefix /usr/node-web-app
    volumes:
      - ./node-web-app:/usr/node-web-app
    ports:
      - 3003:3003
    env_file:
      - ./node-web-app/.env
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    container_name: mysql-node-app
    command: 
      --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    environment:
      #MYSQL_USER: liferaft
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: _liferafttest
      DB_HOSTNAME: mysql
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    healthcheck:
      interval: 2s
      timeout: 20s
      retries: 10
    
volumes: 
  mysql:
  mysql_config: